### ISSUE TITLE
现在还能Login吗

### ISSUE THREAD

**Issue by CompetitiveLin** [david990917/LeetCode-CN-Crawler#3]
https://github.com/david990917/LeetCode-CN-Crawler/blob/265dd53024343233115a8e488623d32e5d2d8693/leetcode-cn-crawler-raw.py#L90
现在这个接口会返回500了，不知道作者会不会出现这种情况

**Comment by ihanwen99** [comment]
我刚做了今天的每日一题，进行尝试，目前确实有这个问题。

**Comment by ihanwen99** [comment]
今天恢复正常了，你可以试一下 :) @CompetitiveLin

**Comment by CompetitiveLin** [comment]
> 今天恢复正常了，你可以试一下 :) @CompetitiveLin

😂我前段时间偶尔会用postman模拟一下登录，有时候第一次可以成功，后面接着就500了，我刚刚也运行了一下脚本，还是500，也不知道你的脚本多运行几次还能不能成功

**Comment by ihanwen99** [comment]
Hello @CompetitiveLin ，我现在把程序升级了一下，使用cookie登陆可以稳定登陆并且获取题目列表✌️
